// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RankingServicio.Infraestructura.Persistencia;

#nullable disable

namespace RankingServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoRanking))]
    partial class ContextoRankingModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ranking")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RankingServicio.Infraestructura.Persistencia.Modelos.EntradaRankingEquipoModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<int>("EtapasCompletadas")
                        .HasColumnType("integer")
                        .HasColumnName("etapas_completadas");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_equipo");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer")
                        .HasColumnName("posicion");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_total");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<DateTime>("UltimaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion_utc");

                    b.HasKey("Id");

                    b.HasIndex("SesionId", "EquipoId")
                        .IsUnique();

                    b.HasIndex("SesionId", "Posicion");

                    b.ToTable("entradas_ranking_equipo", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Infraestructura.Persistencia.Modelos.EntradaRankingParticipanteModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EtapasCompletadas")
                        .HasColumnType("integer")
                        .HasColumnName("etapas_completadas");

                    b.Property<string>("NombreParticipante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_participante");

                    b.Property<Guid>("ParticipanteIdentidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_identidad_id");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer")
                        .HasColumnName("posicion");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_total");

                    b.Property<int>("RespuestasCorrectas")
                        .HasColumnType("integer")
                        .HasColumnName("respuestas_correctas");

                    b.Property<int>("RespuestasTotales")
                        .HasColumnType("integer")
                        .HasColumnName("respuestas_totales");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<DateTime>("UltimaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion_utc");

                    b.HasKey("Id");

                    b.HasIndex("SesionId", "ParticipanteIdentidadId")
                        .IsUnique();

                    b.HasIndex("SesionId", "Posicion");

                    b.ToTable("entradas_ranking_participante", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Infraestructura.Persistencia.Modelos.EventoProcesadoModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TipoEvento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_evento");

                    b.Property<DateTime>("ProcesadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en_utc");

                    b.HasKey("Id", "TipoEvento");

                    b.ToTable("eventos_procesados", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Infraestructura.Persistencia.Modelos.RankingGlobalParticipanteModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EtapasCompletadasTotal")
                        .HasColumnType("integer")
                        .HasColumnName("etapas_completadas_total");

                    b.Property<string>("NombreParticipante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_participante");

                    b.Property<Guid>("ParticipanteIdentidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_identidad_id");

                    b.Property<long>("PuntajeAcumulado")
                        .HasColumnType("bigint")
                        .HasColumnName("puntaje_acumulado");

                    b.Property<int>("SesionesJugadas")
                        .HasColumnType("integer")
                        .HasColumnName("sesiones_jugadas");

                    b.Property<DateTime>("UltimaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion_utc");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteIdentidadId")
                        .IsUnique();

                    b.HasIndex("PuntajeAcumulado");

                    b.ToTable("ranking_global_participante", "ranking");
                });
#pragma warning restore 612, 618
        }
    }
}
