// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RankingServicio.Infraestructura.Persistencia;

#nullable disable

namespace RankingServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoRanking))]
    partial class ContextoRankingModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ranking")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RankingServicio.Dominio.Entidades.Ranking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId")
                        .IsUnique();

                    b.ToTable("rankings", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Dominio.Entidades.RankingEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<long>("Puntaje")
                        .HasColumnType("bigint")
                        .HasColumnName("puntaje");

                    b.Property<Guid>("RankingId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranking_id");

                    b.HasKey("Id");

                    b.HasIndex("RankingId", "EquipoId")
                        .IsUnique();

                    b.ToTable("ranking_equipos", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Dominio.Entidades.RankingParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<Guid>("ParticipanteIdentidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_identidad_id");

                    b.Property<Guid>("ParticipanteSesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_sesion_id");

                    b.Property<long>("Puntaje")
                        .HasColumnType("bigint")
                        .HasColumnName("puntaje");

                    b.Property<Guid>("RankingId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranking_id");

                    b.HasKey("Id");

                    b.HasIndex("RankingId", "ParticipanteSesionId")
                        .IsUnique();

                    b.ToTable("ranking_participantes", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Infraestructura.Persistencia.Modelos.EventoProcesadoModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TipoEvento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_evento");

                    b.Property<DateTime>("ProcesadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en_utc");

                    b.HasKey("Id", "TipoEvento");

                    b.ToTable("eventos_procesados", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Infraestructura.RabbitMq.OutboxMensajeRankingModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en_utc");

                    b.Property<DateTime?>("EnviadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_en_utc");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProximoIntentoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proximo_intento_utc");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("routing_key");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "ProximoIntentoUtc", "CreadoEnUtc");

                    b.ToTable("outbox_ranking", "ranking");
                });

            modelBuilder.Entity("RankingServicio.Dominio.Entidades.RankingEquipo", b =>
                {
                    b.HasOne("RankingServicio.Dominio.Entidades.Ranking", null)
                        .WithMany("Equipos")
                        .HasForeignKey("RankingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RankingServicio.Dominio.Entidades.RankingParticipante", b =>
                {
                    b.HasOne("RankingServicio.Dominio.Entidades.Ranking", null)
                        .WithMany("Participantes")
                        .HasForeignKey("RankingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RankingServicio.Dominio.Entidades.Ranking", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
