// <auto-generated />
using System;
using IdentidadServicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IdentidadServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoIdentidad))]
    [Migration("20260518000001_AgregarValidacionesUnicasUsuario")]
    partial class AgregarValidacionesUnicasUsuario
    {
        protected override void BuildTargetModel(ModelBuilder mb)
        {
            mb.HasDefaultSchema("identidad")
              .HasAnnotation("ProductVersion", "8.0.10")
              .HasAnnotation("Relational:MaxIdentifierLength", 63);

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.UsuarioModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("NombreUsuario").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("nombre_usuario");
                b.Property<string>("IdKeycloak").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("id_keycloak");
                b.Property<int>("Rol").HasColumnType("integer").HasColumnName("rol");
                b.Property<int>("Estado").HasColumnType("integer").HasColumnName("estado");
                b.Property<DateTime>("FechaRegistro").HasColumnType("timestamp with time zone").HasColumnName("fecha_registro");
                b.HasKey("Id");
                b.HasIndex("NombreUsuario").IsUnique();
                b.HasIndex("IdKeycloak").IsUnique();
                b.ToTable("Usuario", "identidad");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UsuarioId").HasColumnType("uuid").HasColumnName("usuario_id");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("nombre");
                b.Property<string>("Apellido").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("apellido");
                b.Property<string>("Correo").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("correo");
                b.Property<string>("Direccion").HasMaxLength(250).HasColumnType("character varying(250)").HasColumnName("direccion");
                b.Property<string>("Telefono").HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("telefono");
                b.Property<int>("Sexo").HasColumnType("integer").HasColumnName("sexo");
                b.Property<DateTime>("FechaNacimiento").HasColumnType("timestamp with time zone").HasColumnName("fecha_nacimiento");
                b.Property<DateTime>("FechaRegistro").HasColumnType("timestamp with time zone").HasColumnName("fecha_registro");
                b.HasKey("Id");
                b.HasIndex("UsuarioId").IsUnique();
                b.HasIndex("Correo").IsUnique();
                b.HasIndex("Telefono").IsUnique().HasFilter("\"telefono\" IS NOT NULL");
                b.ToTable("Persona", "identidad");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.AdministradorModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("PersonaId").HasColumnType("uuid").HasColumnName("persona_id");
                b.Property<string>("CodigoAdministrador").HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("codigo_administrador");
                b.Property<DateTime>("FechaRegistro").HasColumnType("timestamp with time zone").HasColumnName("fecha_registro");
                b.HasKey("Id");
                b.HasIndex("PersonaId").IsUnique();
                b.ToTable("Administrador", "identidad");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.OperadorModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("PersonaId").HasColumnType("uuid").HasColumnName("persona_id");
                b.Property<string>("CodigoOperador").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("codigo_operador");
                b.Property<DateTime>("FechaRegistro").HasColumnType("timestamp with time zone").HasColumnName("fecha_registro");
                b.HasKey("Id");
                b.HasIndex("PersonaId").IsUnique();
                b.HasIndex("CodigoOperador").IsUnique();
                b.ToTable("Operador", "identidad");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("PersonaId").HasColumnType("uuid").HasColumnName("persona_id");
                b.Property<string>("Alias").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("alias");
                b.Property<DateTime>("FechaRegistro").HasColumnType("timestamp with time zone").HasColumnName("fecha_registro");
                b.HasKey("Id");
                b.HasIndex("PersonaId").IsUnique();
                b.HasIndex("Alias").IsUnique();
                b.ToTable("Participante", "identidad");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", b =>
            {
                b.HasOne("IdentidadServicio.Infraestructura.Persistencia.UsuarioModelo", "Usuario")
                    .WithOne("Persona")
                    .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Usuario");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.AdministradorModelo", b =>
            {
                b.HasOne("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "Persona")
                    .WithOne("Administrador")
                    .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.AdministradorModelo", "PersonaId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Persona");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.OperadorModelo", b =>
            {
                b.HasOne("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "Persona")
                    .WithOne("Operador")
                    .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.OperadorModelo", "PersonaId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Persona");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
            {
                b.HasOne("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "Persona")
                    .WithOne("Participante")
                    .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.ParticipanteModelo", "PersonaId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Persona");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.UsuarioModelo", b =>
            {
                b.Navigation("Persona");
            });

            mb.Entity("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", b =>
            {
                b.Navigation("Administrador");
                b.Navigation("Operador");
                b.Navigation("Participante");
            });
        }
    }
}
