// <auto-generated />
using System;
using IdentidadServicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentidadServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoIdentidad))]
    partial class ContextoIdentidadModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidad")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.AdministradorModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoAdministrador")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_administrador");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAdministrador")
                        .IsUnique()
                        .HasFilter("\"codigo_administrador\" IS NOT NULL");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Administrador", "identidad");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.OperadorModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoOperador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_operador");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.HasKey("Id");

                    b.HasIndex("CodigoOperador")
                        .IsUnique();

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Operador", "identidad");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Participante", "identidad");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique()
                        .HasFilter("\"telefono\" IS NOT NULL");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Persona", "identidad");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.UsuarioModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DebeCambiarContrasena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("debe_cambiar_contrasena");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("IdKeycloak")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_keycloak");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("IdKeycloak")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", "identidad");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.AdministradorModelo", b =>
                {
                    b.HasOne("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "Persona")
                        .WithOne("Administrador")
                        .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.AdministradorModelo", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.OperadorModelo", b =>
                {
                    b.HasOne("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "Persona")
                        .WithOne("Operador")
                        .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.OperadorModelo", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
                {
                    b.HasOne("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "Persona")
                        .WithOne("Participante")
                        .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.ParticipanteModelo", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", b =>
                {
                    b.HasOne("IdentidadServicio.Infraestructura.Persistencia.UsuarioModelo", "Usuario")
                        .WithOne("Persona")
                        .HasForeignKey("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.PersonaModelo", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Operador");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("IdentidadServicio.Infraestructura.Persistencia.UsuarioModelo", b =>
                {
                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
