// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SesionesServicio.Infraestructura.Persistencia;

#nullable disable

namespace SesionesServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoSesiones))]
    [Migration("20260710030857_AgregarDuracionSegundosYEjecucionActualSesion")]
    partial class AgregarDuracionSegundosYEjecucionActualSesion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sesiones")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.EquipoModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<string>("ContrasenaHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contrasena_hash");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("LiderParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lider_participante_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_equipo");

                    b.HasKey("Id");

                    b.HasIndex("SesionId", "Nombre")
                        .IsUnique();

                    b.ToTable("Equipo", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.EtapaCompletadaModelo", b =>
                {
                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime>("FechaCompletadaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_completada_utc");

                    b.HasKey("SesionId", "EtapaId");

                    b.HasIndex("SesionId");

                    b.ToTable("EtapaCompletada", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.EvidenciaTesoroModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusquedaId")
                        .HasColumnType("uuid")
                        .HasColumnName("busqueda_id");

                    b.Property<string>("CodigoEnviado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("codigo_enviado");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<bool>("EsValida")
                        .HasColumnType("boolean")
                        .HasColumnName("es_valida");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime>("FechaEnvioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio_utc");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<Guid>("ParticipanteIdentidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_identidad_id");

                    b.Property<int>("PuntosGanados")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_ganados");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId", "EtapaId");

                    b.HasIndex("SesionId", "EtapaId", "EquipoId")
                        .IsUnique()
                        .HasFilter("equipo_id IS NOT NULL AND es_valida");

                    b.HasIndex("SesionId", "EtapaId", "ParticipanteIdentidadId")
                        .IsUnique()
                        .HasFilter("equipo_id IS NULL AND es_valida");

                    b.ToTable("EvidenciaTesoro", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<DateTime?>("FechaUnionEquipo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_union_equipo");

                    b.Property<DateTime>("FechaUnionSesion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_union_sesion");

                    b.Property<Guid>("ParticipanteIdentidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_identidad_id");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("SesionId", "ParticipanteIdentidadId")
                        .IsUnique();

                    b.ToTable("Participante", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.PistaLiberadaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contenido");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime>("FechaLiberacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_liberacion_utc");

                    b.Property<Guid?>("PistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pista_id");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId", "EtapaId");

                    b.HasIndex("SesionId", "EtapaId", "PistaId")
                        .IsUnique()
                        .HasFilter("pista_id IS NOT NULL");

                    b.ToTable("PistaLiberada", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.RespuestaTriviaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean")
                        .HasColumnName("es_correcta");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime>("FechaRespuestaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_respuesta_utc");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<Guid?>("OpcionSeleccionadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("opcion_seleccionada_id");

                    b.Property<Guid>("ParticipanteIdentidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_identidad_id");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pregunta_id");

                    b.Property<int>("PuntosGanados")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_ganados");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<int>("TiempoTardadoMs")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_tardado_ms");

                    b.Property<Guid>("TriviaId")
                        .HasColumnType("uuid")
                        .HasColumnName("trivia_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId", "EtapaId");

                    b.HasIndex("SesionId", "EtapaId", "ParticipanteIdentidadId");

                    b.HasIndex("SesionId", "EtapaId", "PreguntaId", "EquipoId")
                        .IsUnique()
                        .HasFilter("equipo_id IS NOT NULL");

                    b.HasIndex("SesionId", "EtapaId", "PreguntaId", "ParticipanteIdentidadId")
                        .IsUnique()
                        .HasFilter("equipo_id IS NULL");

                    b.ToTable("RespuestaTrivia", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionMisionModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("MisionId");

                    b.HasIndex("SesionId", "MisionId")
                        .IsUnique();

                    b.ToTable("SesionMision", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_acceso");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("DuracionSegundosLimite")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_segundos_limite");

                    b.Property<long?>("EjecucionActualDuracionPausasAcumuladaMs")
                        .HasColumnType("bigint")
                        .HasColumnName("ejecucion_actual_duracion_pausas_acumulada_ms");

                    b.Property<int?>("EjecucionActualDuracionSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("ejecucion_actual_duracion_segundos");

                    b.Property<Guid?>("EjecucionActualEtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_actual_etapa_id");

                    b.Property<DateTime?>("EjecucionActualFechaInicioPausaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ejecucion_actual_fecha_inicio_pausa_utc");

                    b.Property<DateTime?>("EjecucionActualFechaInicioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ejecucion_actual_fecha_inicio_utc");

                    b.Property<Guid?>("EjecucionActualMisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_actual_mision_id");

                    b.Property<Guid?>("EjecucionActualModoDeJuegoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejecucion_actual_modo_de_juego_id");

                    b.Property<int?>("EjecucionActualOrdenGlobal")
                        .HasColumnType("integer")
                        .HasColumnName("ejecucion_actual_orden_global");

                    b.Property<string>("EjecucionActualTipoEtapa")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ejecucion_actual_tipo_etapa");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFinalizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_finalizacion_utc");

                    b.Property<DateTime?>("FechaInicioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_utc");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_programada");

                    b.Property<int?>("MaximoEquipos")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_equipos");

                    b.Property<int?>("MaximoParticipantes")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_participantes");

                    b.Property<int?>("MaximoParticipantesPorEquipo")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_participantes_por_equipo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("OperadorCreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_creador_id");

                    b.Property<string>("TipoSesion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_sesion");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcceso")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("OperadorCreadorId");

                    b.HasIndex("TipoSesion");

                    b.ToTable("Sesion", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.EquipoModelo", b =>
                {
                    b.HasOne("SesionesServicio.Infraestructura.Persistencia.SesionModelo", null)
                        .WithMany("Equipos")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
                {
                    b.HasOne("SesionesServicio.Infraestructura.Persistencia.SesionModelo", null)
                        .WithMany("Participantes")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionMisionModelo", b =>
                {
                    b.HasOne("SesionesServicio.Infraestructura.Persistencia.SesionModelo", null)
                        .WithMany("Misiones")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionModelo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Misiones");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
