// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SesionesServicio.Infraestructura.Persistencia;

#nullable disable

namespace SesionesServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoSesiones))]
    [Migration("20260529202912_InicialSesiones")]
    partial class InicialSesiones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sesiones")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContenidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contenido_id");

                    b.Property<string>("CreadaPorNombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creada_por_nombre_usuario");

                    b.Property<Guid>("CreadaPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("creada_por_usuario_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_programada");

                    b.Property<int>("Modo")
                        .HasColumnType("integer")
                        .HasColumnName("modo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreContenido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_contenido");

                    b.Property<int>("TipoJuego")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_juego");

                    b.HasKey("Id");

                    b.HasIndex("ContenidoId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("TipoJuego");

                    b.ToTable("Sesion", "sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
