// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SesionesServicio.Infraestructura.Persistencia;

#nullable disable

namespace SesionesServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoSesiones))]
    partial class ContextoSesionesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sesiones")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.EquipoModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("LiderParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lider_participante_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId", "Nombre")
                        .IsUnique();

                    b.ToTable("Equipo", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<DateTime?>("FechaUnionEquipo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_union_equipo");

                    b.Property<DateTime>("FechaUnionSesion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_union_sesion");

                    b.Property<Guid>("ParticipanteIdentidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_identidad_id");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("SesionId", "ParticipanteIdentidadId")
                        .IsUnique();

                    b.ToTable("Participante", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionMisionModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("MisionId");

                    b.HasIndex("SesionId", "MisionId")
                        .IsUnique();

                    b.ToTable("SesionMision", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_acceso");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFinalizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_finalizacion_utc");

                    b.Property<DateTime?>("FechaInicioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_utc");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_programada");

                    b.Property<int?>("MaximoEquipos")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_equipos");

                    b.Property<int?>("MaximoParticipantes")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_participantes");

                    b.Property<int?>("MaximoParticipantesPorEquipo")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_participantes_por_equipo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("OperadorCreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_creador_id");

                    b.Property<string>("TipoSesion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_sesion");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcceso")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("OperadorCreadorId");

                    b.HasIndex("TipoSesion");

                    b.ToTable("Sesion", "sesiones");
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.EquipoModelo", b =>
                {
                    b.HasOne("SesionesServicio.Infraestructura.Persistencia.SesionModelo", null)
                        .WithMany("Equipos")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.ParticipanteModelo", b =>
                {
                    b.HasOne("SesionesServicio.Infraestructura.Persistencia.SesionModelo", null)
                        .WithMany("Participantes")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionMisionModelo", b =>
                {
                    b.HasOne("SesionesServicio.Infraestructura.Persistencia.SesionModelo", null)
                        .WithMany("Misiones")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SesionesServicio.Infraestructura.Persistencia.SesionModelo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Misiones");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
