// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartidasServicio.Infraestructura.Persistencia;

#nullable disable

namespace PartidasServicio.Infraestructura.Persistencia.Migrations
{
    [DbContext(typeof(ContextoPartidas))]
    partial class ContextoPartidasModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("partidas")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartidasServicio.Infraestructura.Persistencia.Modelos.PartidaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTime?>("FechaFinUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_utc");

                    b.Property<DateTime?>("FechaInicioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_utc");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionId")
                        .IsUnique();

                    b.ToTable("Partida", "partidas");
                });

            modelBuilder.Entity("PartidasServicio.Infraestructura.Persistencia.Modelos.RespuestaTriviaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EquipoId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipo_id");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean")
                        .HasColumnName("es_correcta");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime>("FechaRespuestaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_respuesta_utc");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.Property<Guid>("OpcionSeleccionadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("opcion_seleccionada_id");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("participante_id");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pregunta_id");

                    b.Property<int>("PuntosGanados")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_ganados");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<long>("TiempoTardadoMs")
                        .HasColumnType("bigint")
                        .HasColumnName("tiempo_tardado_ms");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("SesionId");

                    b.HasIndex("SesionId", "PreguntaId", "EquipoId")
                        .IsUnique()
                        .HasFilter("equipo_id IS NOT NULL");

                    b.HasIndex("SesionId", "PreguntaId", "ParticipanteId")
                        .IsUnique()
                        .HasFilter("equipo_id IS NULL");

                    b.ToTable("RespuestaTrivia", "partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
