// <auto-generated />
using JuegosServicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JuegosServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoJuegos))]
    [Migration("20260530000001_SimplificarEstadosJuegos")]
    partial class SimplificarEstadosJuegos
    {
        protected override void BuildTargetModel(ModelBuilder mb) { }
    }
}
