// <auto-generated />
using System;
using JuegosServicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JuegosServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoJuegos))]
    [Migration("20260525000001_TablaEventoSalida")]
    partial class TablaEventoSalida
    {
        protected override void BuildTargetModel(ModelBuilder mb)
        {
            mb.HasDefaultSchema("juegos")
              .HasAnnotation("ProductVersion", "8.0.10")
              .HasAnnotation("Relational:MaxIdentifierLength", 63);

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.TriviaModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("nombre");
                b.Property<string>("Descripcion").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("descripcion");
                b.Property<Guid>("CreadorId").HasColumnType("uuid").HasColumnName("creador_id");
                b.Property<int>("TiempoLimitePorPregunta").HasColumnType("integer").HasColumnName("tiempo_limite_por_pregunta");
                b.Property<int>("Estado").HasColumnType("integer").HasColumnName("estado");
                b.Property<DateTime>("FechaCreacion").HasColumnType("timestamp with time zone").HasColumnName("fecha_creacion");
                b.HasKey("Id");
                b.HasIndex("Nombre").IsUnique();
                b.ToTable("Trivia", "juegos");
            });

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("TriviaId").HasColumnType("uuid").HasColumnName("trivia_id");
                b.Property<string>("Enunciado").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("enunciado");
                b.Property<int>("PuntajeAsignado").HasColumnType("integer").HasColumnName("puntaje_asignado");
                b.HasKey("Id");
                b.HasIndex("TriviaId");
                b.ToTable("Pregunta", "juegos");
            });

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.OpcionModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("PreguntaId").HasColumnType("uuid").HasColumnName("pregunta_id");
                b.Property<string>("Texto").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)").HasColumnName("texto");
                b.Property<bool>("EsCorrecta").HasColumnType("boolean").HasColumnName("es_correcta");
                b.HasKey("Id");
                b.HasIndex("PreguntaId");
                b.ToTable("Opcion", "juegos");
            });

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.EventoSalidaModelo", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Tipo").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("tipo");
                b.Property<string>("Datos").IsRequired().HasColumnType("text").HasColumnName("datos");
                b.Property<DateTime>("FechaCreacion").HasColumnType("timestamp with time zone").HasColumnName("fecha_creacion");
                b.Property<bool>("Procesado").HasColumnType("boolean").HasColumnName("procesado");
                b.HasKey("Id");
                b.HasIndex("Procesado");
                b.ToTable("EventoSalida", "juegos");
            });

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", b =>
            {
                b.HasOne("JuegosServicio.Infraestructura.Persistencia.Modelos.TriviaModelo", "Trivia")
                    .WithMany("Preguntas")
                    .HasForeignKey("TriviaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Trivia");
            });

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.OpcionModelo", b =>
            {
                b.HasOne("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", "Pregunta")
                    .WithMany("Opciones")
                    .HasForeignKey("PreguntaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Pregunta");
            });

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.TriviaModelo", b =>
            {
                b.Navigation("Preguntas");
            });

            mb.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", b =>
            {
                b.Navigation("Opciones");
            });
        }
    }
}
