// <auto-generated />
using System;
using JuegosServicio.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JuegosServicio.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoJuegos))]
    [Migration("20260602203237_AdaptarBusquedaTesoroSinEtapas")]
    partial class AdaptarBusquedaTesoroSinEtapas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("juegos")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.BusquedaTesoroModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creador_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("BusquedaTesoro", "juegos");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.EventoSalidaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("datos");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<bool>("Procesado")
                        .HasColumnType("boolean")
                        .HasColumnName("procesado");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("EventoSalida", "juegos");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.MisionModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusquedaId")
                        .HasColumnType("uuid")
                        .HasColumnName("busqueda_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("PistaClave")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pista_clave");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("BusquedaId")
                        .IsUnique();

                    b.ToTable("Mision", "juegos");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.OpcionModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean")
                        .HasColumnName("es_correcta");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pregunta_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Opcion", "juegos");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PistaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contenido");

                    b.Property<Guid>("MisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mision_id");

                    b.HasKey("Id");

                    b.HasIndex("MisionId");

                    b.ToTable("Pista", "juegos");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("enunciado");

                    b.Property<int>("PuntajeAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_asignado");

                    b.Property<Guid>("TriviaId")
                        .HasColumnType("uuid")
                        .HasColumnName("trivia_id");

                    b.HasKey("Id");

                    b.HasIndex("TriviaId");

                    b.ToTable("Pregunta", "juegos");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.TriviaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creador_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("TiempoLimitePorPregunta")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_limite_por_pregunta");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Trivia", "juegos");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.MisionModelo", b =>
                {
                    b.HasOne("JuegosServicio.Infraestructura.Persistencia.Modelos.BusquedaTesoroModelo", "BusquedaTesoro")
                        .WithOne("Mision")
                        .HasForeignKey("JuegosServicio.Infraestructura.Persistencia.Modelos.MisionModelo", "BusquedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusquedaTesoro");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.OpcionModelo", b =>
                {
                    b.HasOne("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PistaModelo", b =>
                {
                    b.HasOne("JuegosServicio.Infraestructura.Persistencia.Modelos.MisionModelo", "Mision")
                        .WithMany("Pistas")
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mision");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", b =>
                {
                    b.HasOne("JuegosServicio.Infraestructura.Persistencia.Modelos.TriviaModelo", "Trivia")
                        .WithMany("Preguntas")
                        .HasForeignKey("TriviaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trivia");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.BusquedaTesoroModelo", b =>
                {
                    b.Navigation("Mision");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.MisionModelo", b =>
                {
                    b.Navigation("Pistas");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.PreguntaModelo", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("JuegosServicio.Infraestructura.Persistencia.Modelos.TriviaModelo", b =>
                {
                    b.Navigation("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
